-- seed.sql
-- Dummy data for Laundry Booking & Tracking System

-- =========================================================
-- 0) Mock auth users (for local/dev seed purpose)
-- =========================================================
-- NOTE: This is intended for local/dev only.
-- In production, users should come from Supabase Auth signup flow.

insert into auth.users (
  id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  raw_app_meta_data,
  raw_user_meta_data,
  created_at,
  updated_at
) values
(
  '11111111-1111-1111-1111-111111111111',
  'authenticated',
  'authenticated',
  'admin@laundry.local',
  crypt('Admin123!', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"name":"Admin Laundry"}',
  now(),
  now()
),
(
  '22222222-2222-2222-2222-222222222222',
  'authenticated',
  'authenticated',
  'user1@laundry.local',
  crypt('User12345!', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"name":"Budi"}',
  now(),
  now()
),
(
  '33333333-3333-3333-3333-333333333333',
  'authenticated',
  'authenticated',
  'user2@laundry.local',
  crypt('User12345!', gen_salt('bf')),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"name":"Siti"}',
  now(),
  now()
)
on conflict (id) do nothing;

-- =========================================================
-- 1) Profiles
-- =========================================================
insert into public.profiles (id, name, phone, is_admin)
values
  ('11111111-1111-1111-1111-111111111111', 'Admin Laundry', '081200000001', true),
  ('22222222-2222-2222-2222-222222222222', 'Budi Santoso', '081200000002', false),
  ('33333333-3333-3333-3333-333333333333', 'Siti Aisyah', '081200000003', false)
on conflict (id) do nothing;

-- =========================================================
-- 2) Services (3-5)
-- =========================================================
insert into public.services (id, name, price_per_kg, description, duration)
values
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1', 'Cuci Kiloan', 7000, 'Cuci reguler per kg', '2 hari'),
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2', 'Cuci + Setrika', 10000, 'Cuci, kering, setrika', '2-3 hari'),
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa3', 'Dry Clean', 25000, 'Untuk pakaian khusus', '3 hari'),
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4', 'Express', 15000, 'Pengerjaan cepat prioritas', '6 jam'),
  ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa5', 'Bed Cover / Selimut', 20000, 'Pakaian besar per item/kg', '3 hari')
on conflict (id) do nothing;

-- =========================================================
-- 3) Orders (2-3 dummy orders)
-- order_number auto-generated by trigger
-- =========================================================
insert into public.orders (
  id,
  user_id,
  customer_name,
  phone,
  service_id,
  weight,
  order_type,
  address,
  pickup_date,
  status,
  is_paid
) values
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1',
  '22222222-2222-2222-2222-222222222222',
  'Budi Santoso',
  '081200000002',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa2',
  4.50,
  'pickup',
  'Jl. Melati No. 10, Bandung',
  current_date + 1,
  'washing',
  false
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2',
  '33333333-3333-3333-3333-333333333333',
  'Siti Aisyah',
  '081200000003',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa1',
  null,
  'dropoff',
  'Toko Laundry Cabang A',
  current_date,
  'pending',
  false
),
(
  'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3',
  '22222222-2222-2222-2222-222222222222',
  'Budi Santoso',
  '081200000002',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaa4',
  2.00,
  'pickup',
  'Jl. Mawar No. 22, Bandung',
  current_date - 1,
  'delivered',
  true
)
on conflict (id) do nothing;

-- Ensure total_price is correct for seeded rows
select public.recalculate_order_total_price('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1'::uuid);
select public.recalculate_order_total_price('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2'::uuid);
select public.recalculate_order_total_price('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3'::uuid);

-- =========================================================
-- 4) Tracking logs samples
-- =========================================================
insert into public.tracking_logs (order_id, status, description)
values
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1', 'pending', 'Pesanan dibuat'),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1', 'picked_up', 'Kurir menjemput laundry'),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb1', 'washing', 'Laundry sedang dicuci'),

  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb2', 'pending', 'Pesanan dropoff diterima'),

  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3', 'pending', 'Pesanan dibuat'),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3', 'finished', 'Proses laundry selesai'),
  ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbb3', 'delivered', 'Pesanan telah diantar')
on conflict do nothing;
